version: 1.0.{build}
os: Visual Studio 2015
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- rd /s /q C:\Tools\nuget
- md C:\Tools\nuget
- ps (New-Object Net.WebClient).DownloadFile('http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe', 'C:\Tools\nuget\nuget.exe')
nuget:
  account_feed: true
  project_feed: true
before_build:
- nuget restore OmniXaml.sln
build:
  project: OmniXaml.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: WMHJXgv1b4C+5aomux4ItsdejPsSk+E6L8Yqmraho7YJzdrL2KU6rvYf61/IgsC0
- provider: NuGet
  api_key:
    secure: WMHJXgv1b4C+5aomux4ItsdejPsSk+E6L8Yqmraho7YJzdrL2KU6rvYf61/IgsC0